export const REDUCER_ACTION_TYPES = {
  ADD_USERS: "ADD_USERS",
  UPDATE_USER: "UPDATE_USER",
  UPDATE_LOADING_STATE: "UPDATE_LOADING_STATE",
  DELETE_USER: "DELETE_USER",
  ADD_ERROR: "ADD_ERROR",
  SET_LOCATION: "SET_LOCATION",
};

export const LOCATIONS = [
  "ABU DHABI",
  "AMSTERDAM",
  "AUSTIN",
  "BARCELONA",
  "BENGALURU",
  "BRASÍLIA",
  "BRUSSELS",
  "BUENOS AIRES",
];

export const ERROR_REMOVE_INTERVAL = 2000;

export const LOADING_ITEM_DEFAULT_INDEX = "-1";
